import type { Metadata } from "next";
import "./globals.css";

import { AppBar, Box } from "@mui/material";

import Providers from "@/providers/Providers";

import ControlBar from "@/components/UI/ClientControlBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box sx={{ flexGrow: 1 }}>
            <AppBar position="static" elevation={2}>
              <ControlBar />
            </AppBar>
          </Box>
          {children}
        </Providers>
      </body>
    </html>
  );
}
